- i18n/po/de.po
Fixed Some GFX Errors (Strings too long)
Change Copay Strings to Byteball Strings
Fix
https://dl.dropboxusercontent.com/u/21000833/Byteball/error.JPG
https://dl.dropboxusercontent.com/u/21000833/Byteball/error2.JPG
> Change Copay Strings to Byteball Strings

- i18n/po/hu.po
This pull requests adds the translation file for Hungarian. I haven't added Hungarian to the list of available languages though. That still needs to be done. Could you do that? Or should I look into it?
> Hungarian translation

- i18n/po/fr.po
more French translation and a few fixes
> French Translation

- i18n/po/pt.po
translated almost all missing strings. some might need technical revision
> further translation

- public/views/correspondentDevice.html
- src/js/services/correspondentListService.js
- fix for #90 
- MAX_SAFE_INTEGER undefined on old Chrome fix
> fix #90, MAX_SAFE_INTEGER fix

- i18n/po/id.po
add bahasa indonesia translation
> add bahasa indonesia translation

- cordova/build.sh
- public/views/import.html
- src/js/controllers/import.js
> Fixed choose file in import (Android 4.4)

- public/views/inviteCorrespondentDevice.html
> scrolling on invite page

- public/views/correspondentDevice.html
- public/views/includes/topbar.html
- src/css/main.css
- src/css/mobile.css
> wallet name in dropdown menu

- src/js/partialClient.js
Showing splash instead of wallet when password ist set
> Fix for Issue #139 on Android

- public/views/editCorrespondentDevice.html
- public/views/walletHome.html
- src/css/main.css
- src/js/controllers/walletHome.js
"Clear chat history" is now a button
Wallet home:
"Request specific amount" is now a button
The Byteball address has a larger font size, it is easier to read and to click
The links in the top navigation now have a slight hover effect, as it was not immediately clear that they are clickable from their looks
The button label "Generate QR code" now uses translation (no translations exist yet)
> UI improvements

- src/js/controllers/walletHome.js
> claim fees are now added in core

- src/js/services/fileSystem.js
- fix error "wallet id not found" after having restored a big backup file on mobile
> write files by chunks

- public/views/editCorrespondentDevice.html
- public/views/modals/offer-prosaic-contract.html
- public/views/modals/tx-details.html
- public/views/modals/view-prosaic-contract.html
- src/css/mobile.css
- src/js/controllers/correspondentDevice.js
- src/js/directives/directives.js
+ prosaic contracts design fixes
> Private profiles: multiple save if different fields are disclosed

- public/views/editCorrespondentDevice.html
- src/js/controllers/correspondentDevice.js
+ close contract offer modal window immediately after accepting
> Prosaic contracts:Prosaic contract: sign title instead of hash

- src/css/mobile.css
https://github.com/byteball/obyte-gui-wallet/issues/474
> GitHub issue 474

- public/views/modals/tx-details.html
- public/views/walletHome.html
- src/css/main.css
- src/js/controllers/walletHome.js
- src/js/directives/directives.js
https://obyte.atlassian.net/browse/OB-38
> task ob-38

- package.json
- public/views/walletHome.html
- src/css/main.css
- src/js/controllers/walletHome.js
https://obyte.atlassian.net/browse/OB-36
> Task ob 36

- public/views/includes/menu-item.html
- public/views/includes/menu.html
- public/views/walletHome.html
- src/css/mobile.css
- src/js/controllers/correspondentDevice.js
- src/js/controllers/walletHome.js
- src/js/services/correspondentListService.js
https://obyte.atlassian.net/browse/OB-37
> Notify events update

- appimage/appimage.sh
- appimage/obyte.yml
- src/js/services/profileService.js
- fix `version 'GNUTLS_3_6_3' not found (required by /lib/x86_64-linux-gnu/libcups.so.2)` error in some distros
- fix crash when restoring full backup
- create zipped binaries during appimage creation process
> Linux fixes

- public/views/walletHome.html
Consistent naming of the term "smart contract"
> Consistent naming

- public/views/walletHome.html
- src/js/controllers/walletHome.js
- Add a new "Resend" button in the history tab to replicate the transaction
> Add Resend Feature

- public/views/modals/tx-details.html
- public/views/walletHome.html
- src/css/mobile.css
- src/js/controllers/walletHome.js
- add address next to the name from AddressBook
> Add wallet address next to the name

- public/views/modals/tx-details.html
- public/views/walletHome.html
- src/css/main.css
- src/js/controllers/walletHome.js
> - fix resend feature

- cordova/build.sh
- cordova/config.xml
> fixed build for android and ios

- src/js/controllers/walletHome.js
for showing human readable definition
> do not take watched addresses into account

- public/views/walletHome.html
- src/js/controllers/index.js
- src/js/controllers/walletHome.js
+ tooltip
+ reset position on subwallet change
+ show if 1 asset
+ swipes fixed
> donut chart modifications

- public/views/walletHome.html
- src/css/main.css
- src/css/mobile.css
> get coins button

- public/views/create.html
<label> was causing double click on the switch
> fix single address switch on create page

- public/views/inviteCorrespondentDevice.html
- public/views/walletHome.html
- src/css/main.css
- src/js/controllers/inviteCorrespondentDevice.js
added click to copy hover on invite correspondent page and centered on receive page
> added click to copy on invite correspondent page
